# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/johannes/.larm2/default/gui.ui'
#
# Created: Sun Feb 22 22:52:35 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(762, 524)
        Form.setMinimumSize(QtCore.QSize(762, 524))
        Form.setFocusPolicy(QtCore.Qt.TabFocus)
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(90, 50, 334, 321))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.paramBoxController_2 = ParamBoxController(self.frame)
        self.paramBoxController_2.setMaximumSize(QtCore.QSize(16777215, 46))
        self.paramBoxController_2.setObjectName("paramBoxController_2")
        self.verticalLayout_2.addWidget(self.paramBoxController_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pingpong = ParamBox(self.frame)
        self.pingpong.setObjectName("pingpong")
        self.gridLayout = QtGui.QGridLayout(self.pingpong)
        self.gridLayout.setObjectName("gridLayout")
        self.paramLabel = ParamLabel(self.pingpong)
        self.paramLabel.setObjectName("paramLabel")
        self.gridLayout.addWidget(self.paramLabel, 0, 1, 1, 1)
        self.paramProgress_4 = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress_4.sizePolicy().hasHeightForWidth())
        self.paramProgress_4.setSizePolicy(sizePolicy)
        self.paramProgress_4.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress_4.setMaximum(1000)
        self.paramProgress_4.setParamMin(0.0)
        self.paramProgress_4.setParamMax(99.99)
        self.paramProgress_4.setParamDefault(7.0)
        self.paramProgress_4.setObjectName("paramProgress_4")
        self.gridLayout.addWidget(self.paramProgress_4, 3, 1, 1, 1)
        self.paramProgress_5 = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress_5.sizePolicy().hasHeightForWidth())
        self.paramProgress_5.setSizePolicy(sizePolicy)
        self.paramProgress_5.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress_5.setMaximum(1000)
        self.paramProgress_5.setParamMin(0.0)
        self.paramProgress_5.setParamMax(99.99)
        self.paramProgress_5.setParamDefault(7.0)
        self.paramProgress_5.setObjectName("paramProgress_5")
        self.gridLayout.addWidget(self.paramProgress_5, 4, 1, 1, 1)
        self.paramProgress_6 = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress_6.sizePolicy().hasHeightForWidth())
        self.paramProgress_6.setSizePolicy(sizePolicy)
        self.paramProgress_6.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress_6.setMaximum(1000)
        self.paramProgress_6.setParamMin(0.0)
        self.paramProgress_6.setParamMax(99.99)
        self.paramProgress_6.setParamDefault(7.0)
        self.paramProgress_6.setObjectName("paramProgress_6")
        self.gridLayout.addWidget(self.paramProgress_6, 3, 2, 1, 1)
        self.paramProgress_7 = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress_7.sizePolicy().hasHeightForWidth())
        self.paramProgress_7.setSizePolicy(sizePolicy)
        self.paramProgress_7.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress_7.setMaximum(1000)
        self.paramProgress_7.setParamMin(0.0)
        self.paramProgress_7.setParamMax(99.99)
        self.paramProgress_7.setParamDefault(7.0)
        self.paramProgress_7.setObjectName("paramProgress_7")
        self.gridLayout.addWidget(self.paramProgress_7, 2, 2, 1, 1)
        self.paramProgress_8 = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress_8.sizePolicy().hasHeightForWidth())
        self.paramProgress_8.setSizePolicy(sizePolicy)
        self.paramProgress_8.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress_8.setMaximum(1000)
        self.paramProgress_8.setParamMin(0.0)
        self.paramProgress_8.setParamMax(99.99)
        self.paramProgress_8.setParamDefault(7.0)
        self.paramProgress_8.setObjectName("paramProgress_8")
        self.gridLayout.addWidget(self.paramProgress_8, 4, 2, 1, 1)
        self.paramProgress = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress.sizePolicy().hasHeightForWidth())
        self.paramProgress.setSizePolicy(sizePolicy)
        self.paramProgress.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress.setMaximum(1000)
        self.paramProgress.setParamMin(0.0)
        self.paramProgress.setParamMax(99.99)
        self.paramProgress.setParamDefault(7.0)
        self.paramProgress.setObjectName("paramProgress")
        self.gridLayout.addWidget(self.paramProgress, 2, 1, 1, 1)
        self.paramProgress_11 = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress_11.sizePolicy().hasHeightForWidth())
        self.paramProgress_11.setSizePolicy(sizePolicy)
        self.paramProgress_11.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress_11.setMaximum(1000)
        self.paramProgress_11.setStandardAction(0)
        self.paramProgress_11.setParamMin(0.0)
        self.paramProgress_11.setParamMax(99.99)
        self.paramProgress_11.setParamDefault(7.0)
        self.paramProgress_11.setObjectName("paramProgress_11")
        self.gridLayout.addWidget(self.paramProgress_11, 2, 0, 1, 1)
        self.paramProgress_12 = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress_12.sizePolicy().hasHeightForWidth())
        self.paramProgress_12.setSizePolicy(sizePolicy)
        self.paramProgress_12.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress_12.setMaximum(1000)
        self.paramProgress_12.setParamMin(0.0)
        self.paramProgress_12.setParamMax(99.99)
        self.paramProgress_12.setParamDefault(7.0)
        self.paramProgress_12.setObjectName("paramProgress_12")
        self.gridLayout.addWidget(self.paramProgress_12, 3, 0, 1, 1)
        self.paramProgress_13 = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress_13.sizePolicy().hasHeightForWidth())
        self.paramProgress_13.setSizePolicy(sizePolicy)
        self.paramProgress_13.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress_13.setMaximum(1000)
        self.paramProgress_13.setParamMin(0.0)
        self.paramProgress_13.setParamMax(99.99)
        self.paramProgress_13.setParamDefault(7.0)
        self.paramProgress_13.setObjectName("paramProgress_13")
        self.gridLayout.addWidget(self.paramProgress_13, 4, 0, 1, 1)
        self.paramProgress_14 = ParamProgress(self.pingpong)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramProgress_14.sizePolicy().hasHeightForWidth())
        self.paramProgress_14.setSizePolicy(sizePolicy)
        self.paramProgress_14.setMinimumSize(QtCore.QSize(21, 24))
        self.paramProgress_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.paramProgress_14.setMaximum(1000)
        self.paramProgress_14.setParamMin(0.0)
        self.paramProgress_14.setParamMax(99.99)
        self.paramProgress_14.setParamDefault(7.0)
        self.paramProgress_14.setObjectName("paramProgress_14")
        self.gridLayout.addWidget(self.paramProgress_14, 5, 0, 1, 1)
        self.paramGrid = ParamGrid(self.pingpong)
        self.paramGrid.setParamMin(QtCore.QPointF(0.0, 0.0))
        self.paramGrid.setParamMax(QtCore.QPointF(1.0, 1.0))
        self.paramGrid.setParamDefault(QtCore.QPointF(0.0, 0.0))
        self.paramGrid.setObjectName("paramGrid")
        self.gridLayout.addWidget(self.paramGrid, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.pingpong)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.paramGrid_2 = ParamGrid(Form)
        self.paramGrid_2.setGeometry(QtCore.QRect(510, 150, 100, 100))
        self.paramGrid_2.setParamMin(QtCore.QPointF(0.0, 0.0))
        self.paramGrid_2.setParamMax(QtCore.QPointF(1.0, 1.0))
        self.paramGrid_2.setParamDefault(QtCore.QPointF(0.0, 0.1))
        self.paramGrid_2.setSmooth(20.0)
        self.paramGrid_2.setObjectName("paramGrid_2")
        self.fileBrowserWidget = FileBrowserWidget(Form)
        self.fileBrowserWidget.setGeometry(QtCore.QRect(480, 270, 256, 224))
        self.fileBrowserWidget.setObjectName("fileBrowserWidget")
        self.spinBox = QtGui.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(140, 400, 121, 22))
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.paramSpinbox = ParamSpinBox(Form)
        self.paramSpinbox.setGeometry(QtCore.QRect(290, 390, 111, 21))
        self.paramSpinbox.setMaximum(999999999)
        self.paramSpinbox.setObjectName("paramSpinbox")
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(500, 60, 75, 26))
        self.pushButton.setObjectName("pushButton")
        self.paramPushbutton = ParamPushButton(Form)
        self.paramPushbutton.setGeometry(QtCore.QRect(530, 100, 42, 26))
        self.paramPushbutton.setObjectName("paramPushbutton")
        self.paramThreeStatebutton = ParamThreeStateButton(Form)
        self.paramThreeStatebutton.setGeometry(QtCore.QRect(600, 100, 42, 26))
        self.paramThreeStatebutton.setParamMin(0)
        self.paramThreeStatebutton.setParamMax(2)
        self.paramThreeStatebutton.setParamDefault(1)
        self.paramThreeStatebutton.setObjectName("paramThreeStatebutton")
        self.paramTogglebutton = ParamToggleButton(Form)
        self.paramTogglebutton.setGeometry(QtCore.QRect(660, 150, 42, 26))
        self.paramTogglebutton.setParamDefault(True)
        self.paramTogglebutton.setObjectName("paramTogglebutton")
        self.soundfileViewer_2 = SoundFileViewer(Form)
        self.soundfileViewer_2.setGeometry(QtCore.QRect(30, 390, 100, 30))
        self.soundfileViewer_2.setObjectName("soundfileViewer_2")
        self.paramTogglebutton_2 = ParamCheckBox(Form)
        self.paramTogglebutton_2.setGeometry(QtCore.QRect(120, 480, 24, 13))
        self.paramTogglebutton_2.setObjectName("paramTogglebutton_2")
        self.paramMinMaxSlider = ParamMinMaxSlider(Form)
        self.paramMinMaxSlider.setGeometry(QtCore.QRect(190, 460, 121, 21))
        self.paramMinMaxSlider.setParamMin(QtCore.QPointF(0.0, 0.0))
        self.paramMinMaxSlider.setParamMax(QtCore.QPointF(1.0, 1.0))
        self.paramMinMaxSlider.setParamDefault(QtCore.QPointF(0.0, 1.0))
        self.paramMinMaxSlider.setObjectName("paramMinMaxSlider")
        self.paramLineedit = ParamLineEdit(Form)
        self.paramLineedit.setGeometry(QtCore.QRect(490, 10, 127, 22))
        self.paramLineedit.setObjectName("paramLineedit")

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pingpong, QtCore.SIGNAL("paramsCollected(PyQt_PyObject)"), self.paramBoxController_2.addParams)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.paramBoxController_2.setGroupLabel(QtGui.QApplication.translate("Form", "KingKong", None, QtGui.QApplication.UnicodeUTF8))
        self.paramLabel.setParamPath(QtGui.QApplication.translate("Form", "/default/foo/fim/fap", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress_4.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp5", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress_5.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp8", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress_6.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp6", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress_7.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp3", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress_8.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp9", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp2", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress_11.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp1", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress_12.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp4", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress_13.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp7", None, QtGui.QApplication.UnicodeUTF8))
        self.paramProgress_14.setParamPath(QtGui.QApplication.translate("Form", "/default/path/tp10", None, QtGui.QApplication.UnicodeUTF8))
        self.paramGrid.setParamPath(QtGui.QApplication.translate("Form", "/default/pop/pom", None, QtGui.QApplication.UnicodeUTF8))
        self.paramGrid_2.setParamPath(QtGui.QApplication.translate("Form", "/default/path/fook", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setShortcut(QtGui.QApplication.translate("Form", "Ctrl+C, S", None, QtGui.QApplication.UnicodeUTF8))
        self.paramPushbutton.setParamPath(QtGui.QApplication.translate("Form", "/default/tmp/pushbutton", None, QtGui.QApplication.UnicodeUTF8))
        self.paramThreeStatebutton.setZeroText(QtGui.QApplication.translate("Form", "Kuk", None, QtGui.QApplication.UnicodeUTF8))
        self.paramThreeStatebutton.setOneText(QtGui.QApplication.translate("Form", "Snopp", None, QtGui.QApplication.UnicodeUTF8))
        self.paramThreeStatebutton.setTwoText(QtGui.QApplication.translate("Form", "Penis", None, QtGui.QApplication.UnicodeUTF8))
        self.paramThreeStatebutton.setParamPath(QtGui.QApplication.translate("Form", "/default/tmp/threestate", None, QtGui.QApplication.UnicodeUTF8))
        self.paramTogglebutton.setParamPath(QtGui.QApplication.translate("Form", "/default/tmp/foo", None, QtGui.QApplication.UnicodeUTF8))
        self.paramTogglebutton.setOnText(QtGui.QApplication.translate("Form", "This is on.", None, QtGui.QApplication.UnicodeUTF8))
        self.paramTogglebutton.setOffText(QtGui.QApplication.translate("Form", "This is off.", None, QtGui.QApplication.UnicodeUTF8))
        self.paramTogglebutton_2.setParamPath(QtGui.QApplication.translate("Form", "/default/yes/yes", None, QtGui.QApplication.UnicodeUTF8))
        self.paramMinMaxSlider.setParamPath(QtGui.QApplication.translate("Form", "/default/tmp/yes/kings", None, QtGui.QApplication.UnicodeUTF8))
        self.paramLineedit.setParamPath(QtGui.QApplication.translate("Form", "/default/fim/fipp", None, QtGui.QApplication.UnicodeUTF8))
        self.paramLineedit.setParamDefault(QtGui.QApplication.translate("Form", "rtwar", None, QtGui.QApplication.UnicodeUTF8))

from paramboxcontroller import ParamBox, ParamBoxController
from soundfileviewer import SoundFileViewer
from paramwidgets import ParamLineEdit, ParamToggleButton, ParamCheckBox, ParamMinMaxSlider, ParamSpinBox, ParamPushButton, ParamProgress, ParamGrid, ParamThreeStateButton, ParamLabel
from filebrowser import FileBrowserWidget
