# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paramboxcontroller.ui'
#
# Created: Wed Dec 31 00:13:12 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 52)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainLabel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.mainLabel.setFont(font)
        self.mainLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.mainLabel.setScaledContents(False)
        self.mainLabel.setIndent(0)
        self.mainLabel.setObjectName("mainLabel")
        self.horizontalLayout_2.addWidget(self.mainLabel)
        self.presetComboBox = QtGui.QComboBox(Form)
        self.presetComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.presetComboBox.setEditable(True)
        self.presetComboBox.setMaxVisibleItems(20)
        self.presetComboBox.setObjectName("presetComboBox")
        self.presetComboBox.addItem(QtCore.QString())
        self.horizontalLayout_2.addWidget(self.presetComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.snapshotButton_1 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapshotButton_1.sizePolicy().hasHeightForWidth())
        self.snapshotButton_1.setSizePolicy(sizePolicy)
        self.snapshotButton_1.setMinimumSize(QtCore.QSize(10, 0))
        self.snapshotButton_1.setMaximumSize(QtCore.QSize(20, 20))
        self.snapshotButton_1.setObjectName("snapshotButton_1")
        self.horizontalLayout.addWidget(self.snapshotButton_1)
        self.snapshotButton_2 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapshotButton_2.sizePolicy().hasHeightForWidth())
        self.snapshotButton_2.setSizePolicy(sizePolicy)
        self.snapshotButton_2.setMinimumSize(QtCore.QSize(10, 0))
        self.snapshotButton_2.setMaximumSize(QtCore.QSize(20, 20))
        self.snapshotButton_2.setObjectName("snapshotButton_2")
        self.horizontalLayout.addWidget(self.snapshotButton_2)
        self.snapshotButton_3 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapshotButton_3.sizePolicy().hasHeightForWidth())
        self.snapshotButton_3.setSizePolicy(sizePolicy)
        self.snapshotButton_3.setMinimumSize(QtCore.QSize(10, 0))
        self.snapshotButton_3.setMaximumSize(QtCore.QSize(20, 20))
        self.snapshotButton_3.setObjectName("snapshotButton_3")
        self.horizontalLayout.addWidget(self.snapshotButton_3)
        self.snapshotButton_4 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapshotButton_4.sizePolicy().hasHeightForWidth())
        self.snapshotButton_4.setSizePolicy(sizePolicy)
        self.snapshotButton_4.setMinimumSize(QtCore.QSize(10, 0))
        self.snapshotButton_4.setMaximumSize(QtCore.QSize(20, 20))
        self.snapshotButton_4.setObjectName("snapshotButton_4")
        self.horizontalLayout.addWidget(self.snapshotButton_4)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.snapshotButton_A = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapshotButton_A.sizePolicy().hasHeightForWidth())
        self.snapshotButton_A.setSizePolicy(sizePolicy)
        self.snapshotButton_A.setMinimumSize(QtCore.QSize(10, 0))
        self.snapshotButton_A.setMaximumSize(QtCore.QSize(20, 20))
        self.snapshotButton_A.setObjectName("snapshotButton_A")
        self.horizontalLayout.addWidget(self.snapshotButton_A)
        self.snapshotSlider = ParamBoxControllerSlider(Form)
        self.snapshotSlider.setMaximum(1000)
        self.snapshotSlider.setOrientation(QtCore.Qt.Horizontal)
        self.snapshotSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.snapshotSlider.setTickInterval(500)
        self.snapshotSlider.setObjectName("snapshotSlider")
        self.horizontalLayout.addWidget(self.snapshotSlider)
        self.snapshotButton_B = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapshotButton_B.sizePolicy().hasHeightForWidth())
        self.snapshotButton_B.setSizePolicy(sizePolicy)
        self.snapshotButton_B.setMinimumSize(QtCore.QSize(10, 0))
        self.snapshotButton_B.setMaximumSize(QtCore.QSize(20, 20))
        self.snapshotButton_B.setObjectName("snapshotButton_B")
        self.horizontalLayout.addWidget(self.snapshotButton_B)
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setMinimumSize(QtCore.QSize(30, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.mainLabel.setText(QtGui.QApplication.translate("Form", "Machine Name", None, QtGui.QApplication.UnicodeUTF8))
        self.presetComboBox.setItemText(0, QtGui.QApplication.translate("Form", "Preset name 1", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotButton_1.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotButton_2.setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotButton_3.setText(QtGui.QApplication.translate("Form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotButton_4.setText(QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotButton_A.setText(QtGui.QApplication.translate("Form", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotButton_B.setText(QtGui.QApplication.translate("Form", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Form", "Randomize", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Form", "Misinterpret", None, QtGui.QApplication.UnicodeUTF8))

from paramboxcontrollerslider import ParamBoxControllerSlider

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

